
int main() {
 
 /*  return 0;  */
  
}


  /*
      Notes:
      
 - This is the smallest C program that compiles...
 
 - gcc file.c -Wall: I think it needs the return as well - try with -Wall, -ansi, -pedantic ...
 
  - gcc file.c -ansi:  gives warning if function does not return a value 
 
 - The value of the return should be related to the operations that are done by each specific program
 
 - int main(): 
  It is an example of FUNCTION  (see later when we talk about functions), with return value and optional arguments

  Every executable is generated by a \texttt{main} function,
  or better by ONE AND ONLY ONE main function
 
  The main function contains the program

 - "return" not even specified 
  
 - The body of the function is defined by curly brackets { ... } 
 
 - comment between "slash-star" and "star-slash"  ...


 - "gcc file.c" creates a.out
 - ./a.out to run the program

  */
