
int main() {
 
    
}


  /*
      Notes:
      
 - This is the smallest C program that compiles without warnings
 
 - int main(): 
  It is an example of FUNCTION  (see later when we talk about functions), with return value and optional arguments

  Every executable is generated by a \texttt{main} function,
  or better by ONE AND ONLY ONE main function
 
  The main function contains the program

 - "return" not even specified 
  
 - The body of the function is defined by curly brackets { ... } 
 
 - comment with /* ...


 - "gcc file.c" creates a.out
 - ./a.out to run the program

  */
