
int main() {
 
    
}


  /*
      Notes:
 - main(): inizio programma
  It is an example of FUNCTION  (see later when we talk about functions), with return value and optional arguments

  Every executable is generated by a \texttt{main} function
 
  The main function contains the program

 - commento con /* ...


 - gcc file.c creates a.out
 - ./a.out to run the program

  */
